"""
plot_material_damage.py

Plots FRF comparisons for material damage sweep results (Young's modulus reduction).
Reads from dataset.csv which is generated by material_damage_sweep.py and contains
columns: freq_Hz, node_id, x, y, z, uy_real, uy_imag, label, damage_location_mm, damage_severity.

Produces two plots:
  1. Amplitude — healthy vs varying severity (fixed location) and varying location (fixed severity)
  2. Real & Imaginary + amplitude — healthy vs all damage configurations overlaid

Note: Will not run until material_damage_sweep.py is fixed and dataset.csv is generated.
"""

import csv
import json
import math
import matplotlib.pyplot as plt
import numpy as np
import os

# =============================================================================
# Config
# =============================================================================
dataset_csv = r"C:\Users\coetech\Documents\PyMechanical\Outputs\dataset.csv"
out_dir     = r"C:\Users\coetech\Documents\PyMechanical\Outputs"
os.makedirs(out_dir, exist_ok=True)

# =============================================================================
# Load dataset CSV (requires label, damage_location_mm, damage_severity columns)
# =============================================================================
rows = []
with open(dataset_csv, newline="") as f:
    reader = csv.DictReader(f)
    for row in reader:
        rows.append({
            "freq_Hz":             float(row["freq_Hz"]),
            "node_id":             int(row["node_id"]),
            "x":                   float(row["x"]),
            "y":                   float(row["y"]),
            "z":                   float(row["z"]),
            "uy_real":             float(row["uy_real"]),
            "uy_imag":             float(row["uy_imag"]),
            "label":               row["label"],
            "damage_location_mm":  float(row["damage_location_mm"]),
            "damage_severity":     float(row["damage_severity"]),
        })

print(f"Loaded {len(rows)} rows")

# =============================================================================
# Split into healthy and damage groups
# =============================================================================
healthy_rows = [r for r in rows if r["label"] == "healthy"]
damage_groups = {}
for r in rows:
    if r["label"] == "damaged":
        key = (r["damage_location_mm"], r["damage_severity"])
        damage_groups.setdefault(key, []).append(r)

print(f"Healthy rows: {len(healthy_rows)}")
print(f"Damage configurations: {len(damage_groups)}")

# =============================================================================
# Pick tip node (max Z, near neutral axis)
# =============================================================================
all_x = [r["x"] for r in healthy_rows]
all_y = [r["y"] for r in healthy_rows]
cx = (max(all_x) + min(all_x)) / 2
cy = (max(all_y) + min(all_y)) / 2

z_node_map = {}
for r in healthy_rows:
    z = r["z"]
    dist = (r["x"] - cx)**2 + (r["y"] - cy)**2
    if z not in z_node_map or dist < z_node_map[z][1]:
        z_node_map[z] = (r["node_id"], dist)
z_node_map = {z: nid for z, (nid, _) in z_node_map.items()}

z_vals   = sorted(z_node_map.keys())
tip_node = z_node_map[max(z_vals)]
print(f"Tip node: {tip_node} at z={max(z_vals):.1f} mm")

# =============================================================================
# Helper: build FRF for a node from a row subset
# =============================================================================
def get_frf(node_id, row_subset):
    node_rows = sorted(
        [r for r in row_subset if r["node_id"] == node_id],
        key=lambda r: r["freq_Hz"]
    )
    freqs = [r["freq_Hz"] for r in node_rows]
    amp   = [math.sqrt(r["uy_real"]**2 + r["uy_imag"]**2) for r in node_rows]
    real  = [r["uy_real"] for r in node_rows]
    imag  = [r["uy_imag"] for r in node_rows]
    return freqs, amp, real, imag

# =============================================================================
# Load modal frequencies
# =============================================================================
modal_freqs = []
modal_json_path = os.path.join(out_dir, "modal_frequencies.json")
if os.path.exists(modal_json_path):
    with open(modal_json_path) as f:
        modal_freqs = json.load(f)["frequencies_hz"]
    print(f"Loaded {len(modal_freqs)} modal frequencies")

h_freqs, h_amp, h_real, h_imag = get_frf(tip_node, healthy_rows)
all_locs = sorted(set(loc for loc, _ in damage_groups))
all_sevs = sorted(set(sev for _, sev in damage_groups))

# =============================================================================
# Plot 1: Amplitude — vary severity (fixed middle location)
#                   vary location  (fixed middle severity)
# =============================================================================
mid_loc = all_locs[len(all_locs) // 2]
mid_sev = all_sevs[len(all_sevs) // 2]

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6), sharey=True)

# Left: vary severity
sev_colors = plt.colormaps["Oranges"](np.linspace(0.4, 0.9, len(all_sevs)))
ax1.plot(h_freqs, h_amp, color="steelblue", linewidth=2,
         marker="o", markersize=3, label="Healthy")
for color, sev in zip(sev_colors, all_sevs):
    key = (mid_loc, sev)
    if key in damage_groups:
        freqs, amp, _, _ = get_frf(tip_node, damage_groups[key])
        ax1.plot(freqs, amp, color=color, linewidth=1.5,
                 linestyle="--", marker=".", markersize=3, label=f"Severity {sev:.0%}")
# for mf in modal_freqs:
#     ax1.axvline(x=mf, color="gray", linestyle=":", linewidth=0.8)
ax1.set_xlabel("Frequency (Hz)")
ax1.set_ylabel("Displacement Amplitude |uy| (mm)")
ax1.set_title(f"Varying Severity\n(damage loc = {mid_loc:.1f} mm)")
ax1.legend(fontsize=8)
ax1.grid(True)

# Right: vary location
loc_colors = plt.colormaps["Greens"](np.linspace(0.4, 0.9, len(all_locs)))
ax2.plot(h_freqs, h_amp, color="steelblue", linewidth=2,
         marker="o", markersize=3, label="Healthy")
for color, loc in zip(loc_colors, all_locs):
    key = (loc, mid_sev)
    if key in damage_groups:
        freqs, amp, _, _ = get_frf(tip_node, damage_groups[key])
        ax2.plot(freqs, amp, color=color, linewidth=1.5,
                 linestyle="--", marker=".", markersize=3, label=f"Loc {loc:.1f} mm")
# for mf in modal_freqs:
#     ax2.axvline(x=mf, color="gray", linestyle=":", linewidth=0.8)
ax2.set_xlabel("Frequency (Hz)")
ax2.set_title(f"Varying Location\n(severity = {mid_sev:.0%})")
ax2.legend(fontsize=8)
ax2.grid(True)

fig.suptitle("FRF Amplitude — Healthy vs Damaged (Tip Node)", fontsize=12)
plt.tight_layout()
# plt.savefig(os.path.join(out_dir, "damage_FRF_amplitude.png"), dpi=150)
plt.show()
plt.close(fig)
print("Saved: damage_FRF_amplitude.png")

# =============================================================================
# Plot 2: Real & Imaginary at tip — healthy vs all damage configs
# =============================================================================
fig, axes = plt.subplots(2, 1, figsize=(10, 8), sharex=True)

axes[0].plot(h_freqs, h_real, color="steelblue", linewidth=2,
             marker="o", markersize=3, label="Healthy Real")
axes[0].plot(h_freqs, h_imag, color="cornflowerblue", linewidth=2,
             linestyle="--", marker="s", markersize=3, label="Healthy Imag")
axes[1].plot(h_freqs, h_amp, color="steelblue", linewidth=2,
             marker="o", markersize=3, label="Healthy")

cmap = plt.colormaps["Reds"]
for i, ((loc, sev), d_rows) in enumerate(sorted(damage_groups.items())):
    color = cmap(0.3 + 0.6 * i / max(len(damage_groups) - 1, 1))
    freqs, amp, real, imag = get_frf(tip_node, d_rows)
    lbl = f"loc={loc:.1f} mm, sev={sev:.0%}"
    axes[0].plot(freqs, real, color=color, linewidth=0.9, linestyle="--")
    axes[0].plot(freqs, imag, color=color, linewidth=0.9, linestyle=":")
    axes[1].plot(freqs, amp,  color=color, linewidth=0.9, linestyle="--", label=lbl)

axes[0].set_ylabel("Displacement (mm)")
axes[0].set_title(f"FRF Real & Imaginary — Tip Node {tip_node}")
axes[0].legend(fontsize=7)
axes[0].grid(True)
axes[1].set_xlabel("Frequency (Hz)")
axes[1].set_ylabel("Amplitude |uy| (mm)")
axes[1].legend(fontsize=7, ncol=2)
axes[1].grid(True)

plt.tight_layout()
# plt.savefig(os.path.join(out_dir, "damage_FRF_tip.png"), dpi=150)
plt.show()
plt.close(fig)
print("Saved: damage_FRF_tip.png")

print(f"\nAll plots saved to {out_dir}")
